# Generated by Django 4.1 on 2022-09-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_sucursal'),
        ('tarjetas', '0002_alter_tarjeta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='card_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tarjetas.cardbrand'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
